# Generated by Django 5.1.4 on 2025-05-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('chofer_particular', 'Chofer Particular'), ('chofer_empresa', 'Chofer Empresa')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoferEmpresa',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registroUsuarios.usuario')),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('seguro_url', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChoferParticular',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registroUsuarios.usuario')),
                ('dni', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
                ('seguro_url', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registroUsuarios.usuario')),
                ('dni', models.CharField(max_length=20)),
                ('preferencia_contacto', models.CharField(default='whatsapp', max_length=50)),
            ],
        ),
    ]
