# Generated by Django 5.1.4 on 2025-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
