# Generated by Django 5.2.1 on 2025-05-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuarios', '0002_usuario_nombreusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('capacidad_kg', models.FloatField()),
                ('tiene_acoplado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choferparticular',
            name='vehiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registroUsuarios.vehiculo'),
        ),
    ]
